from pathlib import Path

from smog3 import parity_direct


def test_parity_direct_skips_cleanly_without_perl(monkeypatch, tmp_path: Path):
    monkeypatch.setattr(parity_direct, "_perl_ready", lambda: False)
    rc = parity_direct.main(["--cases", "1", "--report-json", str(tmp_path / "r.json")])
    assert rc == 4
    txt = (tmp_path / "r.json").read_text()
    assert "Perl dependencies missing" in txt


def test_parity_report_structure_when_run_cases_skipped(monkeypatch):
    monkeypatch.setattr(parity_direct, "_perl_ready", lambda: False)
    report = parity_direct.run_cases([1, 21])
    assert report["skipped"] is True
    assert "Perl dependencies missing" in report["reason"]


def test_compare_existing_dirs(tmp_path: Path):
    b = tmp_path / "b"; c = tmp_path / "c"
    b.mkdir(); c.mkdir()
    for fn in ["model.top", "model.gro", "model.ndx", "model.contacts"]:
        (b / fn).write_text("same\n")
        (c / fn).write_text("same\n")
    report = parity_direct.compare_existing_dirs(b, c)
    assert report["ok"] is True
    rc = parity_direct.main(["--compare-existing", "--baseline-dir", str(b), "--candidate-dir", str(c), "--report-json", str(tmp_path / "rep.json")])
    assert rc == 0


def test_compare_existing_ignores_only_top_header_metadata(tmp_path: Path):
    b = tmp_path / "b"; c = tmp_path / "c"
    b.mkdir(); c.mkdir()
    (b / "model.top").write_text("; generated by SMOG2\n; host path\n\n[ defaults ]\n1 1 no\n")
    (c / "model.top").write_text("; generated by SMOG3\n[ defaults ]\n1 1 no\n")
    for fn in ["model.gro", "model.ndx", "model.contacts"]:
        (b / fn).write_text("same\n")
        (c / fn).write_text("same\n")
    report = parity_direct.compare_existing_dirs(b, c)
    assert report["ok"] is True
    assert report["comparisons"]["model.top"]["ignored"] == "topology header metadata before first section"


def test_compare_existing_keeps_top_section_values_strict(tmp_path: Path):
    b = tmp_path / "b"; c = tmp_path / "c"
    b.mkdir(); c.mkdir()
    (b / "model.top").write_text("; generated by SMOG2\n[ defaults ]\n1 1 no\n")
    (c / "model.top").write_text("; generated by SMOG3\n[ defaults ]\n1 2 no\n")
    for fn in ["model.gro", "model.ndx", "model.contacts"]:
        (b / fn).write_text("same\n")
        (c / fn).write_text("same\n")
    report = parity_direct.compare_existing_dirs(b, c)
    assert report["ok"] is False
    assert report["comparisons"]["model.top"]["match"] is False


def test_compare_existing_reports_missing_candidate_files(tmp_path: Path):
    b = tmp_path / "b"; c = tmp_path / "c"
    b.mkdir(); c.mkdir()
    for fn in ["model.top", "model.gro", "model.ndx", "model.contacts"]:
        (b / fn).write_text("baseline\n")
    report = parity_direct.compare_existing_dirs(b, c)
    assert report["ok"] is False
    for fn in ["model.top", "model.gro", "model.ndx", "model.contacts"]:
        assert report["comparisons"][fn]["reason"] == "missing file"


def test_compare_existing_accepts_files_absent_on_both_sides(tmp_path: Path):
    b = tmp_path / "b"; c = tmp_path / "c"
    b.mkdir(); c.mkdir()
    for fn in ["model.top", "model.gro", "model.ndx"]:
        (b / fn).write_text("same\n")
        (c / fn).write_text("same\n")
    report = parity_direct.compare_existing_dirs(b, c)
    assert report["ok"] is True
    assert report["comparisons"]["model.contacts"]["ignored"] == "both files absent"


def test_compare_existing_ignores_only_xml_header_metadata(tmp_path: Path):
    b = tmp_path / "b"; c = tmp_path / "c"
    b.mkdir(); c.mkdir()
    for fn in ["model.top", "model.gro", "model.ndx", "model.contacts"]:
        (b / fn).write_text("same\n")
        (c / fn).write_text("same\n")
    (b / "model.xml").write_text("<!-- generated by SMOG2 -->\n<OpenSMOGforces>\n <contacts/>\n</OpenSMOGforces>\n")
    (c / "model.xml").write_text("<!-- generated by SMOG3 -->\n<OpenSMOGforces>\n <contacts/>\n</OpenSMOGforces>\n")
    report = parity_direct.compare_existing_dirs(b, c, include_xml=True)
    assert report["ok"] is True
    assert report["comparisons"]["model.xml"]["ignored"] == "OpenSMOG XML generated comment metadata before root element"
