from __future__ import annotations

from pathlib import Path

from smog3 import parity_direct, smog2_native
from smog3.adjustpdb_native import main as adjustpdb_main


def test_gro_numeric_fields_wrap_like_smog2() -> None:
    assert smog2_native._gro_field_number(99999) == 99999
    assert smog2_native._gro_field_number(100000) == 0
    assert smog2_native._gro_field_number(100001) == 1


def test_adjustpdb_default_terminal_names_with_insertion_codes(tmp_path: Path) -> None:
    pdb = tmp_path / "input.pdb"
    pdb.write_text(
        "\n".join(
            [
                "ATOM      1  N   GLY A   1      0.000   0.000   0.000  1.00  1.00           N  ",
                "ATOM      2  CA  GLY A   1      1.000   0.000   0.000  1.00  1.00           C  ",
                "ATOM      3  C   GLY A   1      2.000   0.000   0.000  1.00  1.00           C  ",
                "ATOM      4  O   GLY A   1      3.000   0.000   0.000  1.00  1.00           O  ",
                "ATOM      5  N   GLY A   1A     4.000   0.000   0.000  1.00  1.00           N  ",
                "ATOM      6  CA  GLY A   1A     5.000   0.000   0.000  1.00  1.00           C  ",
                "ATOM      7  C   GLY A   1A     6.000   0.000   0.000  1.00  1.00           C  ",
                "ATOM      8  O   GLY A   1A     7.000   0.000   0.000  1.00  1.00           O  ",
                "ATOM      9  OXT GLY A   1A     8.000   0.000   0.000  1.00  1.00           O  ",
                "TER",
                "",
            ]
        )
    )
    out = tmp_path / "adjusted.pdb"

    assert adjustpdb_main(["-i", str(pdb), "-insertTER", "-o", str(out)]) == 0

    atom_lines = [line for line in out.read_text().splitlines() if line.startswith("ATOM")]
    assert atom_lines[0][22:26].strip() == "1"
    assert atom_lines[4][22:26].strip() == "2"
    assert {line[17:21].strip() for line in atom_lines[4:]} == {"GLYT"}


def test_topology_comparator_accepts_format_only_layout_and_ulp(tmp_path: Path) -> None:
    baseline = tmp_path / "baseline.top"
    candidate = tmp_path / "candidate.top"
    baseline.write_text(
        "\n".join(
            [
                "; generated by SMOG2",
                "[ defaults ]",
                "1 1 no 1 1",
                "[ bonds ]",
                "3\t4 \t1\t1.422431018e-01\t1.000000000e+04",
                "[ exclusions ]",
                "3\t22 ",
                "",
            ]
        )
    )
    candidate.write_text(
        "\n".join(
            [
                "; generated by SMOG3",
                "",
                "[ defaults ]",
                "  1      1         no        1       1",
                "",
                "[ bonds ]",
                "3\t4\t1\t1.422431017e-01\t1.000000000e+04",
                "[ exclusions ]",
                "3\t22",
                "",
            ]
        )
    )

    result = parity_direct._compare_file(baseline, candidate)

    assert result["match"] is True
    assert "whitespace layout" in result["ignored"]
