from .template import INTERACTIONS, RESIDUES, ATOM_NAME_HASH
from .config import VERSION
import datetime
import socket
import os

def write_topology(top_file, atom_info, bonds, angles, dihedrals, pairs, exclusions, defaults, mol_name="Macromolecule", nrexcl=3):
    with open(top_file, 'w') as f:
        # Header
        date = datetime.datetime.now().strftime("%a %b %d %H:%M:%S %Y")
        hostname = socket.gethostname()
        f.write(f"; Structure-based \"SMOG\" model for use with GROMACS, NAMD, or OpenMM\n")
        f.write(f"; Generated by the SMOG tool version {VERSION}\n")
        f.write(f"; date: {date}\n")
        f.write(f"; hostname: {hostname}\n")
        f.write("\n")

        # Defaults
        f.write("[ defaults ]\n")
        f.write("; nbfunc comb-rule gen-pairs fudgeLJ fudgeQQ\n")
        gen_pairs = defaults.get('gen-pairs', 'no')
        nbfunc = defaults.get('nbfunc', 1)
        comb_rule = defaults.get('gmx-combination-rule', 1)
        fudge_lj = defaults.get('fudgeLJ', 1.0)
        fudge_qq = defaults.get('fudgeQQ', 1.0)
        f.write(f"  {nbfunc}      {comb_rule}         {gen_pairs}        {fudge_lj}       {fudge_qq}\n")
        f.write("\n")

        # Atomtypes
        f.write("[ atomtypes ]\n")
        if comb_rule == 1:
            f.write("; name  mass     charge    ptype c6            c12\n")
        else:
            f.write("; name  mass     charge    ptype  sigma   epsilon\n")

        # Collect present atomtypes from atom_info (pdb atoms) mapped to templates
        # We need a set of used atom types.
        # atom_info has res_name and atom_name.
        used_nb_types = set()
        for atom in atom_info:
            res_name = atom['res_name']
            atom_name = atom['atom_name']
            if res_name in RESIDUES and atom_name in RESIDUES[res_name]['atoms']:
                nb_type = RESIDUES[res_name]['atoms'][atom_name]['nbType']
                used_nb_types.add(nb_type)

        # Write interactions['nonbonds'] for used types
        for nb_type in sorted(used_nb_types):
            if nb_type in INTERACTIONS['nonbonds']:
                params = INTERACTIONS['nonbonds'][nb_type]
                mass = params['mass']
                charge = params['charge']
                ptype = params['ptype']
                p1 = params.get('c6', params.get('sigma', 0.0))
                p2 = params.get('c12', params.get('epsilon', 0.0))
                f.write(f"{nb_type:<6s} {mass:8.4f} {charge:10.6f}  {ptype:1s}     {p1:13.5e} {p2:13.5e}\n")
        f.write("\n")

        # Moleculetype
        f.write("[ moleculetype ]\n")
        f.write("; name       nrexcl\n")
        f.write(f" {mol_name}    {nrexcl}\n")
        f.write("\n")

        # Atoms
        f.write("[ atoms ]\n")
        f.write(";  nr        type   resnr residue atom   cgnr   charge\n")
        for atom in atom_info:
            res_name = atom['res_name']
            atom_name = atom['atom_name']
            nb_type = RESIDUES[res_name]['atoms'][atom_name]['nbType']
            charge = RESIDUES[res_name]['atoms'][atom_name]['charge']
            if charge is None:
                if nb_type in INTERACTIONS['nonbonds']:
                    charge = INTERACTIONS['nonbonds'][nb_type]['charge']
                else:
                    charge = 0.0

            f.write(f"{atom['atom_num']:6d} {nb_type:10s} {atom['res_counter']:6d} {res_name:6s} {atom_name:6s} {atom['atom_num']:6d} {charge:9.6f}\n")
        f.write("\n")

        # Bonds
        f.write("[ bonds ]\n")
        f.write(";ai\taj\tfunc\t r0(nm)\t         Kb\n")
        for bond in bonds:
            # bond is dict {'i': ..., 'j': ..., 'v': ...} where v is formatted string
            # But wait, bonded.py calculate_bonds returns list of dicts with 'v' as string line
            f.write(bond['v'])
        f.write("\n")

        # Angles
        f.write("[ angles ]\n")
        f.write(";ai\taj\tak\tfunc\t th0(deg)        Ka\n")
        for angle in angles:
            f.write(angle['v'])
        f.write("\n")

        # Dihedrals
        f.write("[ dihedrals ]\n")
        f.write(";ai\taj\tak\tal\tfunc\t phi0(deg)       Kd              mult\n")
        for dihed in dihedrals:
            f.write(dihed['v'])
        f.write("\n")

        # Pairs
        if pairs:
            f.write("[ pairs ]\n")
            f.write(";ai\taj\ttype\t A               B\n")
            for pair in pairs:
                f.write(pair) # Assuming pre-formatted string
            f.write("\n")

        # Exclusions
        if exclusions:
            f.write("[ exclusions ]\n")
            f.write(";ai\taj\n")
            for excl in exclusions:
                f.write(excl) # Assuming pre-formatted string
            f.write("\n")

        # System
        f.write("[ system ]\n")
        f.write("; name\n")
        f.write(f"  {mol_name}\n")
        f.write("\n")

        # Molecules
        f.write("[ molecules ]\n")
        f.write("; name            #molec\n")
        f.write(f"  {mol_name}   1\n")
        f.write("\n")

    print(f"{os.path.abspath(top_file)} written")
