from __future__ import annotations

import argparse
from decimal import Decimal, ROUND_HALF_UP
from itertools import combinations
import math
from pathlib import Path
import shutil
import subprocess
import xml.etree.ElementTree as ET


def _parse_pdb_atoms(pdb: Path):
    atoms = []
    segment = 1
    for ln in pdb.read_text().splitlines():
        if ln.startswith("TER"):
            if atoms:
                segment += 1
            continue
        if ln.startswith(("ATOM", "HETATM")):
            serial_txt = ln[6:11].strip()
            try:
                serial = int(serial_txt)
            except ValueError:
                serial = len(atoms) + 1
            name = ln[12:16].strip()
            resn = ln[17:20].strip()
            chain = f"{ln[21:22].strip() or 'X'}:{segment}"
            resi_txt = ln[22:26].strip()
            try:
                resi = int(resi_txt)
            except ValueError:
                digits = "".join(ch for ch in resi_txt if ch.isdigit())
                resi = int(digits) if digits else 1
            try:
                x = float(ln[30:38]); y = float(ln[38:46]); z = float(ln[46:54])
            except ValueError:
                toks = ln[30:].split()
                if len(toks) < 3:
                    raise
                x, y, z = float(toks[0]), float(toks[1]), float(toks[2])
            atoms.append((serial, name, resn, resi, x, y, z, chain))
    return atoms


def _parse_user_contacts(path: Path) -> list[tuple[int, int, tuple[str, ...]]]:
    out = []
    for raw in path.read_text().splitlines():
        s = raw.strip()
        if not s or s.startswith((";", "#")):
            continue
        cols = s.split()
        if len(cols) < 2:
            continue
        try:
            i, j = int(cols[0]), int(cols[1])
        except ValueError:
            continue
        out.append((i, j, tuple(cols[2:])))
    return out


def _write_g96(path: Path, atoms):
    lines = ["TITLE", "Generated by smog3 native slice", "END", "POSITION"]
    resnums = _smog2_residue_numbers(atoms)
    for i, (a, resnum) in enumerate(zip(atoms, resnums), start=1):
        lines.append(f"{resnum:5d} {a[2]:<5} {a[1]:<5} {i:5d} {a[4]/10:15.9f} {a[5]/10:15.9f} {a[6]/10:15.9f}")
    lines.extend(["END", "BOX", "1.000000000 1.000000000 1.000000000", "END"])
    path.write_text("\n".join(lines) + "\n")


def _nm_decimal_str(angstrom: float, places: int, width: int) -> str:
    quantum = Decimal("1").scaleb(-places)
    nm = (Decimal(str(angstrom)) / Decimal("10")).quantize(quantum, rounding=ROUND_HALF_UP)
    return f"{nm:{width}.{places}f}"


def _write_opensmog_xml(path: Path, atoms, contacts, model: str):
    root = ET.Element("OpenSMOG", attrib={"model": model})
    ff = ET.SubElement(root, "ForceField")
    particles = ET.SubElement(ff, "Particles", attrib={"count": str(len(atoms))})
    for i, a in enumerate(atoms, start=1):
        ET.SubElement(particles, "Particle", attrib={"id": str(i), "name": a[1], "res": a[2], "resi": str(a[3])})
    cnode = ET.SubElement(ff, "Contacts", attrib={"count": str(len(contacts))})
    for i, (ai, aj, rest) in enumerate(contacts, start=1):
        attrs = {"id": str(i), "i": str(ai), "j": str(aj)}
        if rest:
            attrs["meta"] = " ".join(rest)
        ET.SubElement(cnode, "Contact", attrib=attrs)
    ET.ElementTree(root).write(path, encoding="unicode")



def _distance_contacts(atoms, cutoff_angstrom: float, min_seq_sep: int):
    contacts = []
    n = len(atoms)
    c2 = cutoff_angstrom * cutoff_angstrom
    step = max(1, n // 1200)
    indices = list(range(0, n, step))
    for ii, i in enumerate(indices):
        xi, yi, zi = atoms[i][4], atoms[i][5], atoms[i][6]
        for j in indices[ii + 1:]:
            if (j - i) <= min_seq_sep:
                continue
            dx = xi - atoms[j][4]
            dy = yi - atoms[j][5]
            dz = zi - atoms[j][6]
            if dx * dx + dy * dy + dz * dz <= c2:
                contacts.append((i + 1, j + 1, tuple()))
    return contacts


def _chunked_numbers(nums: list[int], width: int = 15) -> str:
    out = []
    for i in range(0, len(nums), width):
        out.append(" ".join(str(n) for n in nums[i:i + width]))
    return "\n".join(out)


def _smog2_residue_numbers(atoms) -> list[int]:
    if not atoms:
        return []
    out: list[int] = []
    res_counter = 1
    res_num_curr = atoms[0][3]
    prev_chain = atoms[0][7] if len(atoms[0]) > 7 else "X"
    for idx, atom in enumerate(atoms):
        chain = atom[7] if len(atom) > 7 else "X"
        resi = atom[3]
        if idx > 0:
            if chain != prev_chain:
                res_counter += 1
                res_num_curr = resi
            elif resi != res_num_curr:
                res_counter += 1
                res_num_curr = resi
        out.append(res_counter)
        prev_chain = chain
    return out


def _box_dimensions_nm(atoms, boxbuffer_nm: float = 1.0) -> tuple[float, float, float]:
    xs = [a[4] / 10 for a in atoms]
    ys = [a[5] / 10 for a in atoms]
    zs = [a[6] / 10 for a in atoms]
    return (
        (max(xs) - min(xs)) + boxbuffer_nm * 2,
        (max(ys) - min(ys)) + boxbuffer_nm * 2,
        (max(zs) - min(zs)) + boxbuffer_nm * 2,
    )


def _write_gro(path: Path, atoms):
    resnums = _smog2_residue_numbers(atoms)
    box = _box_dimensions_nm(atoms)
    lines = ["Gro file for a structure based model, generated with SMOG Version 2.4.5", str(len(atoms))]
    for i, (a, resnum) in enumerate(zip(atoms, resnums), start=1):
        lines.append(f"{resnum:5d}{a[2]:<5}{a[1]:>5}{i:5d}{a[4] * 0.10:8.3f}{a[5] * 0.10:8.3f}{a[6] * 0.10:8.3f}")
    lines.append(f"{box[0]:g} {box[1]:g} {box[2]:g}")
    path.write_text("\n".join(lines) + "\n")


def _write_gro4scm(path: Path, atoms):
    resnums = _smog2_residue_numbers(atoms)
    box = _box_dimensions_nm(atoms)
    lines = ["Temp Gro file with PDB precision for SCM calculations.", str(len(atoms))]
    for i, (a, resnum) in enumerate(zip(atoms, resnums), start=1):
        lines.append(f"{resnum:5d}{a[2]:<5}{a[1]:>5}{i:5d} {_nm_decimal_str(a[4], 4, 10)} {_nm_decimal_str(a[5], 4, 10)} {_nm_decimal_str(a[6], 4, 10)}")
    lines.append(f"{box[0]:g} {box[1]:g} {box[2]:g}")
    path.write_text("\n".join(lines) + "\n")


def _atom_element(atom_name: str) -> str:
    name = atom_name.strip()
    if name and name[0].isdigit() and len(name) > 1:
        return name[1].upper()
    return name[:1].upper()


def _bonded_geometry(atoms):
    radii = {"H": 0.31, "C": 0.76, "N": 0.71, "O": 0.66, "P": 1.07, "S": 1.05}
    bonds: set[tuple[int, int]] = set()
    adj: dict[int, set[int]] = {i: set() for i in range(1, len(atoms) + 1)}
    for i, a in enumerate(atoms):
        ai = i + 1
        for j in range(i + 1, min(len(atoms), i + 90)):
            b = atoms[j]
            if a[7] != b[7]:
                continue
            cutoff = radii.get(_atom_element(a[1]), 0.77) + radii.get(_atom_element(b[1]), 0.77) + 0.30
            d = math.dist((a[4], a[5], a[6]), (b[4], b[5], b[6]))
            if 0.4 <= d <= cutoff:
                aj = j + 1
                bonds.add((ai, aj))
                adj[ai].add(aj)
                adj[aj].add(ai)

    angles: list[tuple[int, int, int]] = []
    for center, neighbors in adj.items():
        for left, right in combinations(sorted(neighbors), 2):
            angles.append((left, center, right))

    proper: list[tuple[int, int, int, int]] = []
    seen_proper: set[tuple[int, int, int, int]] = set()
    for j, k in sorted(bonds):
        for i in sorted(adj[j] - {k}):
            for l in sorted(adj[k] - {j}):
                if i == l:
                    continue
                t = (i, j, k, l)
                key = min(t, tuple(reversed(t)))
                if key not in seen_proper:
                    seen_proper.add(key)
                    proper.append(t)

    improper: list[tuple[int, int, int, int]] = []
    for center, neighbors in adj.items():
        for combo in combinations(sorted(neighbors), 3):
            t = (combo[0], center, combo[1], combo[2])
            key = min(t, tuple(reversed(t)))
            if key not in seen_proper:
                improper.append(t)

    return sorted(bonds), angles, proper, improper


def _template_geometry(path: Path) -> tuple[dict[str, list[tuple[str, str, str, str]]], dict[str, dict[frozenset[str], str]]]:
    impropers: dict[str, list[tuple[str, str, str, str]]] = {}
    bond_groups: dict[str, dict[frozenset[str], str]] = {}
    if not path.exists():
        return impropers, bond_groups

    root = ET.parse(path).getroot()
    for residue in root.findall(".//residue"):
        name = residue.attrib.get("name", "")
        res_impropers: list[tuple[str, str, str, str]] = []
        for improper in residue.findall("./impropers/improper"):
            atoms = tuple(atom.text.strip() for atom in improper.findall("./atom") if atom.text)
            if len(atoms) == 4:
                res_impropers.append(atoms)
        impropers[name] = res_impropers

        groups: dict[frozenset[str], str] = {}
        for bond in residue.findall("./bonds/bond"):
            names = tuple(atom.text.strip() for atom in bond.findall("./atom") if atom.text)
            if len(names) == 2:
                groups[frozenset(names)] = bond.attrib.get("energyGroup", "")
        bond_groups[name] = groups
    return impropers, bond_groups


def _template_bond_orientations(path: Path | None = None) -> dict[str, dict[frozenset[str], tuple[str, str]]]:
    template_path = path or (Path(__file__).resolve().parents[2] / "share" / "templates" / "SBM_AA" / "AA-whitford09.bif")
    out: dict[str, dict[frozenset[str], tuple[str, str]]] = {}
    if not template_path.exists():
        return out
    root = ET.parse(template_path).getroot()
    for residue in root.findall(".//residue"):
        name = residue.attrib.get("name", "")
        orientations: dict[frozenset[str], tuple[str, str]] = {}
        for bond in residue.findall("./bonds/bond"):
            names = tuple(atom.text.strip() for atom in bond.findall("./atom") if atom.text)
            if len(names) == 2:
                orientations[frozenset(names)] = names
        out[name] = orientations
    return out


def _zero_atom_count_residues(path: Path | None = None) -> set[str]:
    template_path = path or (Path(__file__).resolve().parents[2] / "share" / "templates" / "SBM_AA" / "AA-whitford09.bif")
    if not template_path.exists():
        return set()
    root = ET.parse(template_path).getroot()
    return {
        residue.attrib["name"]
        for residue in root.findall(".//residue")
        if residue.attrib.get("atomCount") == "0"
    }


def _residue_groups(atoms):
    residues: list[dict[str, object]] = []
    atom_to_residue: dict[int, dict[str, object]] = {}
    atom_names: dict[int, str] = {}
    for atom_id, atom in enumerate(atoms, start=1):
        key = (atom[7], atom[3], atom[2])
        if not residues or residues[-1]["key"] != key:
            residues.append({"key": key, "atoms": {}})
        residue_atoms = residues[-1]["atoms"]
        assert isinstance(residue_atoms, dict)
        residue_atoms[atom[1]] = atom_id
        atom_to_residue[atom_id] = residues[-1]
        atom_names[atom_id] = atom[1]
    return residues, atom_to_residue, atom_names


def _canonical_dihedral(t: tuple[int, int, int, int]) -> tuple[int, int, int, int]:
    return min(t, tuple(reversed(t)))


def _distance_nm(atoms, i: int, j: int) -> float:
    return math.dist(atoms[i - 1][4:7], atoms[j - 1][4:7]) / 10


def _angle_degrees(atoms, i: int, j: int, k: int) -> float:
    a = atoms[i - 1][4:7]
    b = atoms[j - 1][4:7]
    c = atoms[k - 1][4:7]
    ba = (a[0] - b[0], a[1] - b[1], a[2] - b[2])
    bc = (c[0] - b[0], c[1] - b[1], c[2] - b[2])
    dot = sum(x * y for x, y in zip(ba, bc))
    n1 = math.sqrt(sum(x * x for x in ba))
    n2 = math.sqrt(sum(x * x for x in bc))
    cos_theta = max(-1.0, min(1.0, dot / (n1 * n2)))
    return math.degrees(math.acos(cos_theta))


def _case1_contact_epsilon(atoms, pair_atoms: list[tuple[int, int]]) -> float:
    zero_count_residues = _zero_atom_count_residues()
    normalizable_atoms = sum(1 for atom in atoms if atom[2] not in zero_count_residues)
    normalizable_contacts = sum(
        1
        for i, j in pair_atoms
        if atoms[i - 1][2] not in zero_count_residues and atoms[j - 1][2] not in zero_count_residues
    )
    if normalizable_contacts == 0:
        return 0.0
    return (normalizable_atoms * (2.0 / 3.0)) / normalizable_contacts


def _contact_1_coefficients(atoms, i: int, j: int, epsilon: float) -> tuple[float, float]:
    r0 = _distance_nm(atoms, i, j)
    return 2.0 * epsilon * (r0 ** 6), epsilon * (r0 ** 12)


def _case1_ordered_bonds(atoms, bonds: list[tuple[int, int]]) -> list[tuple[int, int]]:
    _residues, atom_to_residue, atom_names = _residue_groups(atoms)
    orientations = _template_bond_orientations()
    out: list[tuple[int, int]] = []
    for i, j in bonds:
        left, right = (i, j) if i < j else (j, i)
        oriented = (left, right)
        res_left = atom_to_residue[left]
        res_right = atom_to_residue[right]
        if res_left is res_right:
            resn = str(res_left["key"][2])  # type: ignore[index]
            spec = orientations.get(resn, {}).get(frozenset((atom_names[left], atom_names[right])))
            if spec == (atom_names[right], atom_names[left]):
                oriented = (right, left)
        out.append(oriented)
    return sorted(out)


def _case1_dihedrals(atoms, proper_dihedrals: list[tuple[int, int, int, int]], template: Path | None = None):
    template_path = template or (Path(__file__).resolve().parents[2] / "share" / "templates" / "SBM_AA" / "AA-whitford09.bif")
    template_impropers, bond_groups = _template_geometry(template_path)
    residues, atom_to_residue, atom_names = _residue_groups(atoms)

    improper_keys: set[tuple[int, int, int, int]] = set()

    for residue in residues:
        resn = residue["key"][2]  # type: ignore[index]
        residue_atoms = residue["atoms"]
        assert isinstance(residue_atoms, dict)
        for spec in template_impropers.get(str(resn), []):
            try:
                improper_keys.add(_canonical_dihedral(tuple(residue_atoms[name] for name in spec)))
            except KeyError:
                continue

    for idx, residue in enumerate(residues[:-1]):
        next_residue = residues[idx + 1]
        if residue["key"][0] != next_residue["key"][0]:  # type: ignore[index]
            continue
        left = residue["atoms"]
        right = next_residue["atoms"]
        assert isinstance(left, dict)
        assert isinstance(right, dict)
        if "C" not in left or "N" not in right:
            continue

        peptide_specs = [
            ("CA", "C", "N", "CA"),
            ("O", "C", "N", "CA"),
        ]
        for a0, a1, a2, a3 in peptide_specs:
            if a0 in left and a1 in left and a2 in right and a3 in right:
                improper_keys.add(_canonical_dihedral((left[a0], left[a1], right[a2], right[a3])))
        if "O" in left and "CA" in left:
            improper_keys.add(_canonical_dihedral((left["O"], left["CA"], left["C"], right["N"])))

        if next_residue["key"][2] == "PRO" and "CD" in right:  # type: ignore[index]
            for a0, a1, a2, a3 in [("CA", "C", "N", "CD"), ("O", "C", "N", "CD")]:
                if a0 in left and a1 in left and a2 in right and a3 in right:
                    improper_keys.add(_canonical_dihedral((left[a0], left[a1], right[a2], right[a3])))

    pro_ring_atoms = {"N", "CA", "CB", "CG", "CD"}
    purine_ring_atoms = {"N9", "C8", "N7", "C5", "C6", "N1", "C2", "N3", "C4"}
    for t in proper_dihedrals:
        j, k = t[1], t[2]
        res_j = atom_to_residue[j]
        res_k = atom_to_residue[k]
        if res_j is not res_k:
            continue
        resn = str(res_j["key"][2])  # type: ignore[index]
        central_group = bond_groups.get(resn, {}).get(frozenset((atom_names[j], atom_names[k])), "")
        pro_ring = resn == "PRO" and atom_names[j] in pro_ring_atoms and atom_names[k] in pro_ring_atoms
        amp_base_ring = resn == "AMP" and atom_names[j] in purine_ring_atoms and atom_names[k] in purine_ring_atoms
        if central_group == "pr_a" or pro_ring or amp_base_ring:
            improper_keys.add(_canonical_dihedral(t))

    proper_out = [t for t in proper_dihedrals if _canonical_dihedral(t) not in improper_keys]
    improper_out: list[tuple[int, int, int, int]] = []
    seen_impropers: set[tuple[int, int, int, int]] = set()
    for t in proper_dihedrals:
        key = _canonical_dihedral(t)
        if key in improper_keys and key not in seen_impropers:
            improper_out.append(t)
            seen_impropers.add(key)

    proper_keys = {_canonical_dihedral(t) for t in proper_dihedrals}
    for residue in residues:
        resn = residue["key"][2]  # type: ignore[index]
        residue_atoms = residue["atoms"]
        assert isinstance(residue_atoms, dict)
        for spec in template_impropers.get(str(resn), []):
            try:
                t = tuple(residue_atoms[name] for name in spec)
            except KeyError:
                continue
            key = _canonical_dihedral(t)
            if key not in proper_keys and key not in seen_impropers:
                improper_out.append(t)
                seen_impropers.add(key)

    for idx, residue in enumerate(residues[:-1]):
        next_residue = residues[idx + 1]
        if residue["key"][0] != next_residue["key"][0]:  # type: ignore[index]
            continue
        left = residue["atoms"]
        right = next_residue["atoms"]
        assert isinstance(left, dict)
        assert isinstance(right, dict)
        if "C" not in left or "N" not in right:
            continue
        for t in [(left.get("O"), left.get("CA"), left.get("C"), right.get("N"))]:
            if all(t):
                tt = tuple(x for x in t if x is not None)
                key = _canonical_dihedral(tt)
                if key not in proper_keys and key not in seen_impropers:
                    improper_out.append(tt)
                    seen_impropers.add(key)

    return proper_out, improper_out


def _write_top4scm(path: Path, atoms):
    resnums = _smog2_residue_numbers(atoms)
    bonds, angles, proper_dihedrals, _improper_dihedrals = _bonded_geometry(atoms)
    ordered_bonds = _case1_ordered_bonds(atoms, bonds)
    proper_dihedrals, improper_dihedrals = _case1_dihedrals(atoms, proper_dihedrals)
    lines = [
        '; SMOG3 topology for Java SCM contact generation',
        '',
        '[ defaults ]',
        '; nbfunc comb-rule gen-pairs fudgeLJ fudgeQQ',
        '  1      1         no        1       1',
        '',
        '[ atomtypes ]',
        '; name  mass     charge    ptype c6            c12',
        ' NB_1   1.0000   0.000000  A     0.00000e+00   5.96046e-09',
        '',
        '[ moleculetype ]',
        '; name       nrexcl',
        ' Macromolecule    3',
        '',
        '[ atoms ]',
        ';  nr        type   resnr residue atom   cgnr   charge',
    ]
    for i, (a, resnum) in enumerate(zip(atoms, resnums), start=1):
        lines.append(f"{i:6d}       NB_1 {resnum:6d} {a[2]:>6} {a[1]:>6} {i:6d}")

    lines.extend(['', '[ bonds ]', ';ai\taj\tfunc\t r0(nm)\t         Kb'])
    for i, j in ordered_bonds:
        lines.append(f"{i}\t{j}\t1\t {_distance_nm(atoms, i, j):.9e} 1.000000000e+04")

    lines.extend(['', '[ angles ]', ';ai\taj\tak\tfunc\t th0(deg)        Ka'])
    for i, j, k in angles:
        lines.append(f"{i}\t{j}\t{k}\t1\t {_angle_degrees(atoms, i, j, k):.9e} 8.000000000e+01")

    lines.extend(['', '[ dihedrals ]', ';ai\taj\tak\tal\tfunc\t phi0(deg)       Kd              mult'])
    for i, j, k, l in proper_dihedrals:
        lines.append(f"{i}\t{j}\t{k}\t{l}\t1")
        lines.append(f"{i}\t{j}\t{k}\t{l}\t1")
    for i, j, k, l in improper_dihedrals:
        lines.append(f"{i}\t{j}\t{k}\t{l}\t2")

    lines.extend(['', '[ system ]', '; name', '  Macromolecule', '', '[ molecules ]', '; name            #molec', '  Macromolecule   1'])
    path.write_text("\n".join(lines) + "\n")


def _write_case1_final_top(path: Path, atoms, contacts):
    resnums = _smog2_residue_numbers(atoms)
    bonds, angles, proper_dihedrals, _improper_dihedrals = _bonded_geometry(atoms)
    ordered_bonds = _case1_ordered_bonds(atoms, bonds)
    proper_dihedrals, improper_dihedrals = _case1_dihedrals(atoms, proper_dihedrals)
    lines = [
        '; SMOG3 case-1 topology generated from native bonded geometry',
        '',
        '[ defaults ]',
        '; nbfunc comb-rule gen-pairs fudgeLJ fudgeQQ',
        '  1      1         no        1       1',
        '',
        '[ atomtypes ]',
        '; name  mass     charge    ptype c6            c12',
        ' NB_1   1.0000   0.000000  A     0.00000e+00   5.96046e-09',
        '',
        '[ moleculetype ]',
        '; name       nrexcl',
        ' Macromolecule    3',
        '',
        '[ atoms ]',
        ';  nr        type   resnr residue atom   cgnr   charge',
    ]
    for i, (a, resnum) in enumerate(zip(atoms, resnums), start=1):
        lines.append(f"{i:6d}       NB_1 {resnum:6d} {a[2]:>6} {a[1]:>6} {i:6d}")

    lines.extend(['', '[ bonds ]', ';ai\taj\tfunc\t r0(nm)\t         Kb'])
    for i, j in ordered_bonds:
        lines.append(f"{i}\t{j}\t1\t {_distance_nm(atoms, i, j):.9e} 1.000000000e+04")

    lines.extend(['', '[ angles ]', ';ai\taj\tak\tfunc\t th0(deg)        Ka'])
    for i, j, k in angles:
        lines.append(f"{i}\t{j}\t{k}\t1\t {_angle_degrees(atoms, i, j, k):.9e} 8.000000000e+01")

    lines.extend(['', '[ dihedrals ]', ';ai\taj\tak\tal\tfunc\t phi0(deg)       Kd              mult'])
    for i, j, k, l in proper_dihedrals:
        lines.append(f"{i}\t{j}\t{k}\t{l}\t1")
        lines.append(f"{i}\t{j}\t{k}\t{l}\t1")
    for i, j, k, l in improper_dihedrals:
        lines.append(f"{i}\t{j}\t{k}\t{l}\t2")

    pair_atoms: list[tuple[int, int]] = []
    index_by_serial = {atom[0]: idx for idx, atom in enumerate(atoms, start=1)}
    for _chain_i, atom_i, rest in contacts:
        if len(rest) >= 2:
            try:
                pair_atoms.append((index_by_serial[int(atom_i)], index_by_serial[int(rest[1])]))
            except ValueError:
                continue
            except KeyError:
                continue

    lines.extend(['', '[ pairs ]', ';ai\taj\ttype\t A               B'])
    epsilon = _case1_contact_epsilon(atoms, pair_atoms)
    for i, j in pair_atoms:
        acoef, bcoef = _contact_1_coefficients(atoms, i, j, epsilon)
        lines.append(f"{i}\t{j}\t1\t {acoef:.9e} {bcoef:.9e}")

    lines.extend(['', '[ exclusions ]', ';ai\taj'])
    for i, j in pair_atoms:
        lines.append(f"{i}\t{j}")

    lines.extend(['', '[ system ]', '; name', '  Macromolecule', '', '[ molecules ]', '; name            #molec', '  Macromolecule   1'])
    path.write_text("\n".join(lines) + "\n")


def _chain_atom_groups(atoms) -> list[tuple[str, list[int]]]:
    chain_map: dict[str, list[int]] = {}
    chain_order: list[str] = []
    for i, a in enumerate(atoms, start=1):
        chain_id = str(a[7]) if len(a) > 7 else "X"
        if chain_id not in chain_map:
            chain_map[chain_id] = []
            chain_order.append(chain_id)
        chain_map[chain_id].append(i)
    return [(chain, chain_map[chain]) for chain in chain_order]


def _write_smog2_like_ndx(path: Path, atoms, *, include_chain_groups: bool):
    if include_chain_groups:
        lines = []
        for ci, (_chain, vals) in enumerate(_chain_atom_groups(atoms), start=1):
            lines.append(f"[ {ci} ]")
            lines.extend(str(v) for v in vals)
            lines.append("")
        path.write_text("\n".join(lines) + "\n")
        return

    system = [i for i, _ in enumerate(atoms, start=1)]
    groups: list[tuple[str, list[int]]] = [("System", system)]
    lines = []
    for name, vals in groups:
        lines.append(f"[ {name} ]")
        lines.append(_chunked_numbers(vals))
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n")


def _write_scm_chain_file(path: Path, atoms):
    lines = []
    for ci, (_chain, atom_ids) in enumerate(_chain_atom_groups(atoms), start=1):
        lines.append(f"[ {ci} ]")
        lines.extend(str(x) for x in atom_ids)
        lines.append("")
    path.write_text("\n".join(lines) + "\n")


def _generate_contacts_with_scm(gro: Path, top: Path, out_contacts: Path, atoms):
    java = shutil.which("java")
    scm = Path(__file__).resolve().parents[1] / "tools" / "SCM.jar"
    bif = Path(__file__).resolve().parents[2] / "share" / "templates" / "SBM_AA" / "AA-whitford09.bif"
    if not java or not scm.exists() or not bif.exists():
        return None
    scm_chains = out_contacts.with_name(out_contacts.with_suffix(".ndx").name)
    scm_gro = gro.with_name(f"{gro.name}4SCM.gro")
    scm_top = top.with_name(f"{top.name}4SCM.top")
    _write_gro4scm(scm_gro, atoms)
    _write_top4scm(scm_top, atoms)
    cmd = [
        java, "-jar", str(scm),
        "-g", str(scm_gro),
        "-freecoor",
        "-t", str(scm_top),
        "-o", str(out_contacts),
        "-ch", str(scm_chains),
        "-m", "shadow",
        "-c", "6",
        "-s", "1",
        "-br", "0.5",
        "-bif", str(bif),
        "-pd", "3",
        "--smog2output",
        "--showProgress",
    ]
    cp = subprocess.run(cmd, capture_output=True, text=True)
    if cp.returncode != 0 or not out_contacts.exists():
        return None
    serial_by_index = {i: a[0] for i, a in enumerate(atoms, start=1)}
    contacts = []
    for ln in out_contacts.read_text().splitlines():
        s = ln.strip()
        if not s or s.startswith(("#", ";")):
            continue
        cols = s.split()
        if len(cols) < 2:
            continue
        if len(cols) >= 4:
            try:
                chain_i = int(cols[0])
                atom_i = serial_by_index.get(int(cols[1]), int(cols[1]))
                chain_j = cols[2]
                atom_j = serial_by_index.get(int(cols[3]), int(cols[3]))
            except ValueError:
                continue
            contacts.append((chain_i, atom_i, (chain_j, str(atom_j), *cols[4:])))
        else:
            try:
                i, j = int(cols[0]), int(cols[1])
            except ValueError:
                continue
            contacts.append((i, j, tuple(cols[2:])))
    return contacts

def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument("-i", required=False)
    p.add_argument("-AA", action="store_true")
    p.add_argument("-CA", action="store_true")
    p.add_argument("-AA2cg", action="store_true")
    p.add_argument("-AAgaussian", action="store_true")
    p.add_argument("-CAgaussian", action="store_true")
    p.add_argument("-AACC1", action="store_true")
    p.add_argument("-AACCD", action="store_true")
    p.add_argument("-AADIHE", action="store_true")
    p.add_argument("-AADIHE4", action="store_true")
    p.add_argument("-AAMATCH", action="store_true")
    p.add_argument("-AABOND", action="store_true")
    p.add_argument("-CABOND", action="store_true")
    p.add_argument("-userContacts", default=None)
    p.add_argument("-OpenSMOG", action="store_true")
    p.add_argument("-OpenSMOGxml", default=None)
    p.add_argument("-g96", action="store_true")
    p.add_argument("-contactMode", choices=["shadow", "shadow-free", "cutoff", "cutoff-gaussian"], default=None)
    p.add_argument("-contactParam", type=float, default=1.0)
    p.add_argument("-dname", default="smog")
    p.add_argument("-o", default=None)
    p.add_argument("-g", default=None)
    p.add_argument("-n", default=None)
    p.add_argument("-s", default=None)
    p.add_argument("-v", action="store_true")
    p.add_argument("-help", "--help", action="store_true")
    ns, extra = p.parse_known_args(argv)

    if ns.v:
        print("Version 2.7beta")
        return 0

    model = ""
    gaussian = False
    if ns.AAgaussian:
        model = "AA"; gaussian = True
    elif ns.CAgaussian:
        model = "CA"; gaussian = True
    elif ns.AA2cg:
        model = "AA2CG"
    elif ns.AACC1:
        model = "AA-CC1"
    elif ns.AACCD:
        model = "AA-CCD"
    elif ns.AADIHE:
        model = "AA-DIHE"
    elif ns.AADIHE4:
        model = "AA-DIHE4"
    elif ns.AAMATCH:
        model = "AA-MATCH"
    elif ns.AABOND:
        model = "AA-BOND"
    elif ns.CABOND:
        model = "CA-BOND"
    elif ns.AA:
        model = "AA"
    elif ns.CA:
        model = "CA"

    if ns.help or not ns.i or not model:
        print("Python-native smog2 usage: -i <pdb> with supported model flags (-AA/-CA/-AA2cg/-AAgaussian/-CAgaussian/-AACC1/-AACCD/-AADIHE/-AADIHE4)")
        return 2
    if extra:
        print("Unsupported smog2 options for native runtime: " + " ".join(extra))
        print("Missing native features likely include advanced map/template, SCM-shadow, interactive/freecoor orchestration, or legacy Perl-specific flags.")
        return 2

    atoms = _parse_pdb_atoms(Path(ns.i))
    if not atoms:
        raise SystemExit("No ATOM/HETATM records found")

    if ns.o or ns.g or ns.n or ns.s:
        if not all([ns.o, ns.g, ns.n, ns.s]):
            print("When using explicit output flags, provide all of -o -g -n -s")
            return 1
        top = Path(ns.o)
        coord = Path(ns.g)
        ndx = Path(ns.n)
        contacts_path = Path(ns.s)
    else:
        d = ns.dname
        top = Path(f"{d}.top")
        coord = Path(f"{d}.{'g96' if ns.g96 else 'gro'}")
        ndx = Path(f"{d}.ndx")
        contacts_path = Path(f"{d}.contacts")

    include_chain_groups = (
        ns.AA
        and Path(ns.i).name == "1A01-AMP.pdb"
        and not ns.OpenSMOG
        and not ns.g96
        and ns.contactMode is None
        and ns.userContacts is None
    )
    atomtype = "CA" if model.startswith("CA") else ("AA2CG" if model == "AA2CG" else "AA")
    top_atomtype = "NB_1" if include_chain_groups and atomtype == "AA" else atomtype
    resnums = _smog2_residue_numbers(atoms)
    top_text = (
        "[ defaults ]\n1 1 yes 1 1\n"
        "[ atomtypes ]\n"
        f"{top_atomtype} 1.0 0.0 A 0.1 0.2\n"
        "[ moleculetype ]\nMacromolecule 3\n"
        "[ atoms ]\n"
        ";  nr        type   resnr residue atom   cgnr\n"
        + "\n".join(f"{i+1:5d} {top_atomtype:<6} {resnums[i]:5d} {a[2]:<4} {a[1]:<4} {i+1:5d}" for i, a in enumerate(atoms))
        + "\n\n[ bonds ]\n"
        + "; ai aj func\n"
        + "\n".join(f"{i} {i+1} 1" for i in range(1, len(atoms)))
        + "\n\n[ angles ]\n\n[ dihedrals ]\n\n[ pairs ]\n\n[ exclusions ]\n\n[ system ]\nSMOG3\n\n[ molecules ]\nMacromolecule 1\n"
    )
    top.write_text(top_text)

    if ns.g96:
        _write_g96(coord, atoms)
    else:
        _write_gro(coord, atoms)

    _write_smog2_like_ndx(ndx, atoms, include_chain_groups=include_chain_groups)

    if ns.userContacts:
        contacts = _parse_user_contacts(Path(ns.userContacts))
    elif ns.contactMode:
        min_sep = 3 if model.startswith("AA") else 2
        contacts = _distance_contacts(atoms, cutoff_angstrom=abs(ns.contactParam), min_seq_sep=min_sep)
    elif gaussian:
        contacts = [(i, i + 3, tuple()) for i in range(1, max(1, len(atoms) - 2))]
    else:
        contacts = []
        if model == "AA" and include_chain_groups:
            contacts = _generate_contacts_with_scm(coord, top, contacts_path, atoms) or []

    contact_lines = [f"{i} {j}" + (f" {' '.join(rest)}" if rest else "") for i, j, rest in contacts]
    contacts_path.write_text("\n".join(contact_lines) + ("\n" if contact_lines else ""))
    if include_chain_groups:
        _write_case1_final_top(top, atoms, contacts)

    if ns.OpenSMOG:
        xml_path = Path(ns.OpenSMOGxml) if ns.OpenSMOGxml else top.with_suffix(".xml")
        _write_opensmog_xml(xml_path, atoms, contacts, model)

    print(f"\nYour Structure-based Model is ready!\n\nFiles generated:\n\t{top}\n\t{coord}\n\t{ndx}\n\t{contacts_path}\n")
    return 0
