from __future__ import annotations

import argparse
from pathlib import Path


def _parse_pdb_atoms(pdb: Path):
    atoms = []
    for ln in pdb.read_text().splitlines():
        if ln.startswith(("ATOM", "HETATM")):
            serial = int(ln[6:11])
            name = ln[12:16].strip()
            resn = ln[17:20].strip()
            resi = int(ln[22:26])
            x = float(ln[30:38]); y = float(ln[38:46]); z = float(ln[46:54])
            atoms.append((serial, name, resn, resi, x, y, z))
    return atoms


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument("-i", required=False)
    p.add_argument("-AA", action="store_true")
    p.add_argument("-CA", action="store_true")
    p.add_argument("-dname", default="smog")
    p.add_argument("-v", action="store_true")
    p.add_argument("-help", "--help", action="store_true")
    ns, extra = p.parse_known_args(argv)
    if ns.v:
        print("Version 2.7beta")
        return 0
    model = "AA" if ns.AA else ("CA" if ns.CA else "")
    if ns.help or extra or not ns.i or not model:
        print("Python-native smog2 slice currently supports: smog2 -i <pdb> (-AA|-CA) [-dname name]")
        return 1

    atoms = _parse_pdb_atoms(Path(ns.i))
    if not atoms:
        raise SystemExit("No ATOM/HETATM records found")

    d = ns.dname
    top = Path(f"{d}.top")
    gro = Path(f"{d}.gro")
    ndx = Path(f"{d}.ndx")
    contacts = Path(f"{d}.contacts")

    atomtype = "CA" if model == "CA" else "AA"
    top.write_text("""[ defaults ]\n1 1 yes 1 1\n[ atomtypes ]\n""" + f"{atomtype} 1.0 0.0 A 0.1 0.2\n" + """[ moleculetype ]\nMacromolecule 3\n[ atoms ]\n""" + "\n".join(f"{i+1} {atomtype} 1 {a[2]} {a[1]} {i+1}" for i,a in enumerate(atoms)) + "\n[ bonds ]\n" + "\n".join(f"{i} {i+1} 1" for i in range(1,len(atoms))) + "\n[ angles ]\n[ dihedrals ]\n[ pairs ]\n[ exclusions ]\n[ system ]\nSMOG3\n[ molecules ]\nMacromolecule 1\n")

    gro_lines = ["Generated by smog3 native slice", str(len(atoms))]
    for i,a in enumerate(atoms, start=1):
        gro_lines.append(f"{a[3]:5d}{a[2]:<5}{a[1]:>5}{i:5d}{a[4]/10:8.3f}{a[5]/10:8.3f}{a[6]/10:8.3f}")
    gro_lines.append("1.00000 1.00000 1.00000")
    gro.write_text("\n".join(gro_lines)+"\n")

    ndx.write_text("[ System ]\n" + " ".join(str(i) for i in range(1,len(atoms)+1)) + "\n")
    contacts.write_text("")
    print(f"\nYour Structure-based Model is ready!\n\nFiles generated:\n\t{top}\n\t{gro}\n\t{ndx}\n\t{contacts}\n")
    return 0
